### ISSUE TITLE
VCI の Lua スクリプトにおいて、 json.parse が多次元配列をパースできずエラーになる

### ISSUE THREAD

**Issue by oocytanb** [virtual-cast/VCI#20]
## 概要

VCI の Lua スクリプトでは、MoonSharp 由来の `json` モジュールを利用できます。  
`json.parse` に、多次元配列が含まれている JSON 文字列を渡すと、`Unexpected token` エラーが発生するケースがあります。

## 問題が発生する Lua のコード

```
json.parse('{"arr":[[101,102]]}')

実行結果:
Unexpected token : '101,102'
```

期待する結果は、正常に JSON がパースされ、Lua のテーブルとして返されることです。

## 確認した VirtualCast のバージョン

- 2.0.0a (PC ベータ版、ルームとスタジオ両方)
- 1.9.5d (PC 安定板)
- (1.9.5d より前のバージョンでも発生していました)

## 参考リンク

- [json.parse lexer fails on 2D arrays](https://github.com/moonsharp-devs/moonsharp/issues/219)

- VirtualCast 2.0.0a で、JSON 関連における 2件の問題が修正されましたので、多次元配列の問題も修正されると、ありがたく思います。
    - [エスケープされたスラッシュが入ったjsonをパースできない不具合を修正しました。](https://virtualcast.jp/blog/2020/11/virtualcast200a_beta/)
    - [json.serializeで数値のマイナスがパースできない問題を修正しました。](https://virtualcast.jp/wiki/doku.php?id=vci:updatelog:2.0.0a)

**Comment by Santarh** [comment]
バグ報告の方、ありがとうございます。
長らく放置してしまい、申し訳ありません。

今後、より良い VCI 運営を行うために、VCI に対する報告・要望に関しての窓口集約を行う予定です。
これに伴って本リポジトリは UniVCI パッケージの配布に専念するため、一旦のところ Issue 機能を閉じます。

下記窓口をご活用ください。
お問い合わせフォーム https://virtualcast.jp/contact/
公式 Discord コミュニティ https://discord.gg/jtsXVVA
