### ISSUE TITLE
BlendShapeのAnimationがある場合にExportに失敗する

### ISSUE THREAD

**Issue by FujiSunflower** [virtual-cast/VCI#29]
サブアイテムにAnimationコンポーネントが個別についておりBlendShapeのAnimationClipがあるとき、KeyNotFoundExceptionが発生してVCIエクスポートが出来ませんでした。

**Comment by Santarh** [comment]
ご要望の方、承りました。
長らく放置してしまい、申し訳ありません。

今後、より良い VCI 運営を行うために、VCI に対する報告・要望に関しての窓口集約を行う予定です。
これに伴って本リポジトリは UniVCI パッケージの配布に専念するため、一旦のところ Issue 機能を閉じます。

下記窓口をご活用ください。
お問い合わせフォーム https://virtualcast.jp/contact/
公式 Discord コミュニティ https://discord.gg/jtsXVVA
