### ISSUE TITLE
例外の再スロー

### ISSUE THREAD

**Issue by esperecyan** [virtual-cast/VCI#3]
Unityエディタからのエクスポート時に例外が発生した場合、スタックトレースが上書きされ、発生箇所がわかりません。
https://github.com/virtual-cast/VCI/blob/74a509f6d41180fd21a7ea092ef54b3141c0e208/Assets/VCI/UniVCI/Editor/VCIExporterMenu.cs#L64-L67

次のように再スローできないでしょうか。
```C#
            catch
            {
                throw;
            }
```

**Comment by hiroj** [comment]
ご報告ありがとうございます、リスローするように修正致します。

**Comment by esperecyan** [comment]
@hiroj UniVCI-0.31でなぜかまたcatch句が追加されています。
https://github.com/virtual-cast/VCI/commit/9f99f635fc31bd82f57d28b02af87c470611b62f#diff-0ab82f25d63a8df82d04986c5767721c1d9f7a84a128c6c1e90bccecce0049c4R59-R62

ご確認お願いいたします。
