### ISSUE TITLE
メニューからアイテムを出したときの向き

### ISSUE THREAD

**Issue by esperecyan** [virtual-cast/VCI#4]
THE SEED ONLINE上でアイテムを表示するときは手前が正面になりますが、バーチャルキャスト内でアイテムを出したときは奥が正面になります。

とくに装着VCIの場合はこれで適切な場合が多いと思いますが、そうでないアイテムもあるので、設定項目を設けるなどできないでしょうか。

### 正面手前が適切な例
- 壁に貼るもの
    + [バーチャルキャストイベントポスターカレンダー](https://seed.online/user/items/3529bfa5c9e370544c182d929ffd01a415c61b34b3d04ec569498bee26f8d546)
- 正面が見えるように設置するもの
    + [【Vケット3】ぽけもりBOOTH支部](https://seed.online/user/items/3b1e287323b1017b8a22531a2f4accf54413a1df575ee8d5a8cd99ec34953e38)

**Comment by Santarh** [comment]
ご要望の方、承りました。
長らく放置してしまい、申し訳ありません。

今後、より良い VCI 運営を行うために、VCI に対する報告・要望に関しての窓口集約を行う予定です。
これに伴って本リポジトリは UniVCI パッケージの配布に専念するため、一旦のところ Issue 機能を閉じます。

下記窓口をご活用ください。
お問い合わせフォーム https://virtualcast.jp/contact/
公式 Discord コミュニティ https://discord.gg/jtsXVVA
